language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: ekyhJq0gymH9o2oLwdeWiVQ2Z1CxQLnhXHJTVG4NOa7iYaKcluqjM6gbxzJDbGg/MBI0klgL15buj1S9Lzys+IcrISyIe8AXLts1QnH0NQckzgOINry3cHJtvHSwg74IzlAGTqAeDsid7hMTg13Rz7Gx/amhs9oo2oMtFuVGAWDogqtp7whvUsY2uWgKzRvug4B8vzLsD6eLe6A6Gj/TYeWz2Lnoug/6kJGAr5RV9hgya339nMpszJ/cYTB/3UszXJ3/+vV7Grsu44M3wEKyXs4Z3LHPTfdCLvTi2Sx6EZ+cIDFAWT/s1OByTtSiJFVLP/vAWL+dfh6fOMatJXWGavr4tezYsKQvFGOuwQvcTQHLhO7bojtJR0U17ZeXv/E2gr9YjJ+Ivlm9ITE2t69SZH7+YgjQS/OhAMc8OmaIigzYxpSpE9nS7RPicKz7yAlgEn5yuvKTTO1cCj+uo96/nW03yleiYkBNWPMWoHyBBu7930qOnfwmHDTvsmBezqBsTVDJOksMJAtn02X33IkTQc9uBL3MwMWy1bqFt/ja+p23pm+kSnqJtV7BTx9ctZnrbvMQJKNSFVBzwl6bgUZqQqpC01kjS++9rOJ/QMQay+zZjwYfJ7fbEplawMWkH95JBifI6kduMnsQaafO/ZahDRffICxL6dt5IihpHRnfZ9E=
